source 'https://rubygems.org'

gem 'rails', '4.1.6'
gem 'rails-api'
gem 'pg'
gem 'thin'
gem 'active_model_serializers'
gem 'rack-cors', :require => 'rack/cors'
gem 'rails_12factor', group: :production
